[package]
name = "actix_routing_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
env_logger = "0.9.0"

serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
