use actix_web::get;

// Routing Examples
/// Using the `get` attribute to automatically create a resource from this function.
/// NOTE: The struct generated is `pub`.
#[get("/hello_service")]
async fn hello_service() -> &'static str {
    "Hello from service!"
}

// Code generated by Cargo Expand for hello_service
//
// #[allow(non_camel_case_types, missing_docs)]
// pub struct hello_service;
// impl ::actix_web::dev::HttpServiceFactory for hello_service {
//     fn register(self, __config: &mut actix_web::dev::AppService) {
//         async fn hello_service() -> &'static str {
//             "Hello world!"
//         }
//         let __resource = ::actix_web::Resource::new("/hello_service")
//             .name("hello_service")
//             .guard(::actix_web::guard::Get())
//             .to(hello_service);
//         ::actix_web::dev::HttpServiceFactory::register(__resource, __config)
//     }
// }

/// Example that is manually routed.
pub async fn hello_route() -> &'static str {
    "Hello from route!"
}
/// Example that is manually turned into a resource.
pub async fn manual_service() -> &'static str {
    "Hello from manual service!"
}
